# Generated by Django 3.2.7 on 2021-09-16 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_food', '0002_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_shop', models.CharField(max_length=40, verbose_name='Название')),
                ('adress', models.CharField(max_length=40, verbose_name='Адресс')),
            ],
        ),
        migrations.AddField(
            model_name='check',
            name='shop_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api_food.shop', verbose_name='Магазин'),
        ),
    ]
