# Generated by Django 3.2.7 on 2021-09-16 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_food', '0003_auto_20210916_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_code', models.IntegerField()),
                ('phone_code', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_food.customer', verbose_name='Покупатель')),
            ],
        ),
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=20, verbose_name='Штрих-код')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_food.customer', verbose_name='Покупатель')),
                ('verify_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_food.verifyuser', verbose_name='Проверка')),
            ],
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('shop_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api_food.shop', verbose_name='Магазин')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
